apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: jamesfalkner-poi-map-app-dev
  annotations:
    argocd/app-name: jamesfalkner-poi-map-app-dev
    backstage.io/kubernetes-id: jamesfalkner-poi-map-app-dev
    backstage.io/kubernetes-namespace: jamesfalkner
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/instance=jamesfalkner-poi-map-app-dev'
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: rosa916-rvhvd/jamesfalkner-frontend
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - typescript
    - angular
    - workshop
  links:
    - url: https://console-openshift-console.apps.rosa916.9nln.p1.openshiftapps.com/dev-pipelines/ns/jamesfalkner/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.rosa916.9nln.p1.openshiftapps.com/k8s/ns/jamesfalkner/deployments/jamesfalkner-poi-map-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.rosa916.9nln.p1.openshiftapps.com/#https://github.com/rosa916-rvhvd/jamesfalkner-frontend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: http://jamesfalkner-poi-map-app-jamesfalkner.apps.rosa916.9nln.p1.openshiftapps.com
      title: Map
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/jamesfalkner"
  system: workshop-system-jamesfalkner
  consumesApis:
    - gateway-api-jamesfalkner
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-jamesfalkner
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:default/jamesfalkner"
